import numpy as np
a = "Hello world"
print(a)
b = np.array([1, 2, 3])
print(b)
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
d = np.array([1, 2, 3, 4, 5, 6], ndmin=2)
print(d)
e = np.array([1, 2, 3], dtype=complex)
print(e)
f = np.array([[1, 2, 3], [4, 5, 6]])
print(f.shape)
print(f.reshape(3, 2))
g = np.arange(24)
print(g)
print(g.ndim)
print(g.shape)
print(g.reshape(2, 4, 3))
x = [1, 2, 3]
z = np.asarray(x)
print(z)